# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20160217_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
